// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2026 Born2BSalty
//
// `workspace_state_loader` — the replacement for the previous plan's
// "orchestrator bridge". Three `pub fn` operations that move per-modlist
// state between the persisted `ModlistWorkspaceState`
// (`modlists/<id>/workspace.json`) and the orchestrator's owned
// `WizardState`:
//
//   1. `populate_wizard_state_from_workspace` — workspace → `WizardState`,
//      called on workspace open / modlist swap. **Real Step 2 + Step 3
//      reconstruction** (not `game_install`-only — that was the PR#11
//      failure this loader exists to not repeat). It marks the persisted
//      `ComponentRef`s `checked` + `selected_order` on the scanned Step 2
//      mods, re-derives the per-mod tri-state, and rebuilds the Step 3
//      ordered item list via BIO's own canonical
//      `bio::app::controller::step3_sync::build_step3_items` (the exact
//      function BIO uses to keep Step 3 in sync with Step 2 selections).
//
//   2. `extract_workspace_state_from_wizard` — `WizardState` → workspace,
//      the inverse. Called on save-draft / nav-away / debounce (those
//      callers land in Runs 2/4 — extract ships unwired this run, which is
//      correct).
//
//   3. `sync_paths_from_settings` — a one-time re-assert of the canonical
//      `Step1Settings` path/tool fields into `wizard_state.step1`, called on
//      workspace open (from `populate`). Per-frame is unnecessary: Settings
//      → Paths edits the *same* in-memory `wizard_state.step1`, so paths are
//      live by construction. Pure copy; touches nothing else.
//
// Uses BIO's `pub` / `pub(crate)` API only (same-crate reachable per the
// Phase-1 lib+bin split). No BIO source modification; no field is private;
// no method is added.
//
// **Step 2 expand-state note.** `ModlistWorkspaceState.expand_state` has no
// `WizardState` counterpart: BIO's Step 2 tree mod/parent expand/collapse is
// `egui::CollapsingHeader` *frame memory*, not a `WizardState` field. The
// canonical persisted store for it is `ModlistWorkspaceState` itself, so the
// loader carries the map through on extract (preserving whatever was loaded)
// and is a no-op for it on populate. This is an architectural fact, not the
// order-reconstruction make-or-break (Step 3 *group* collapse, which DOES
// live on `WizardState`, round-trips for real). The plan (P6.T1) phrases this
// as the `expand_state`-"equivalent" and treats workspace-model field
// alignment as free.
//
// C5 — never invoked during install: the rail-nav lock (Phase 7 P7.T9b)
// prevents nav-into-a-different-workspace mid-install, so populate is never
// reached with a running install.
//
// SPEC: §13.1 (per-modlist workspace state), §13.14 (persistence timing),
//       §5.1 (game choice immutable per workspace).

// rationale: the numeric parses are component-id strings → i64; on the rare
// non-numeric synthetic row we skip rather than panic (handled explicitly).
#![allow(clippy::must_use_candidate)]

use crate::app::controller::step3_sync;
use crate::app::state::{Step2ModState, Step3ItemState, WizardState};
use crate::registry::model::{Game, ModlistEntry};
use crate::registry::workspace_model::{ComponentRef, ModlistWorkspaceState};
use crate::settings::store::SettingsStore;

/// Synthetic component id BIO's `step3_sync` uses for the mod-header parent
/// rows. These rows are regenerated by `build_step3_items`; they are never
/// persisted (extract skips them) and never matched against the scan.
const PARENT_PLACEHOLDER_ID: &str = "__PARENT__";

// ---------------------------------------------------------------------------
// populate: ModlistWorkspaceState → WizardState
// ---------------------------------------------------------------------------

/// Write a modlist's persisted workspace state into the orchestrator's owned
/// `WizardState`. Called on workspace open / modlist swap (P6.T1 / P6.T12).
///
/// - `step1.game_install` ← `entry.game` (the per-modlist game — SPEC §5.1).
///   This write lives only in the orchestrator's in-memory `WizardState`; it
///   does **not** reach `bio_settings.json` (the snapshot masks it — see
///   `OrchestratorApp::bio_settings_snapshot`).
/// - Path / tool fields ← copied from the loaded `Step1Settings` (via
///   `sync_paths_from_settings`).
/// - Step 2 selection ← each `order_<tab>` `ComponentRef` re-marks its
///   matching scanned `Step2ComponentState` as `checked` with its position
///   as `selected_order`; the per-mod tri-state `checked` is re-derived.
/// - Step 3 order ← rebuilt from the now-marked Step 2 mods via BIO's
///   canonical `step3_sync::build_step3_items`.
/// - Step 5 ← reset to defaults (install state is per-active-install, not
///   per-workspace-load — Phase 7 owns it).
pub fn populate_wizard_state_from_workspace(
    workspace: &ModlistWorkspaceState,
    entry: &ModlistEntry,
    settings_store: &SettingsStore,
    wizard_state: &mut WizardState,
) {
    // 1. Per-modlist game (SPEC §5.1). In-memory only.
    wizard_state.step1.game_install = entry.game.to_legacy_string().to_string();

    // 2. Global paths / tools from Settings — the one-time open re-assert.
    //    This is the ONLY caller: Settings → Paths edits the shared
    //    `wizard_state.step1` directly, so no per-frame sync is needed.
    sync_paths_from_settings(settings_store, wizard_state);

    // 3. **Reset the in-memory scanned Step-2/3 set on every modlist
    //    load/swap (Fix-Run 1, Bug B).** The orchestrator owns ONE shared
    //    `WizardState`; a modlist swap must NOT inherit the previous
    //    modlist's scanned mod vectors. `apply_order_to_mods` (below) only
    //    re-marks `checked`/`selected_order` on whatever mods are *already
    //    in memory* — so without this reset a **fresh** modlist (no scan
    //    yet) would show the previously-open modlist's scanned mods, and a
    //    **draft** swap's own re-scan would be blocked because
    //    `step2_resume_scan::maybe_trigger_resume_scan` is gated on
    //    "Step-2 set empty + no scan in flight" (`step2_resume_scan.rs`):
    //    a stale non-empty set keeps it from re-firing. Clearing the
    //    scanned set + its transients here makes a fresh modlist start
    //    empty (its own scan runs when the user scans) and re-arms the
    //    cold-resume gate so a draft restores its OWN scan + selections on
    //    an A→B→A swap. Step 3 is rebuilt from the now-empty set just below
    //    (and a second time by the resume-scan reconcile once a draft's
    //    re-scan lands — the existing cold-resume path). SPEC §13.1
    //    ("per-modlist … replaces single-workspace in-memory state").
    reset_scanned_step2_set(wizard_state);

    // 3b. Step 2 selection reconstruction. Mark each persisted ComponentRef's
    //    scanned component `checked` + `selected_order`; then re-derive the
    //    per-mod tri-state. After the reset above the scanned set is empty on
    //    a cold resume / fresh modlist (nothing matches — correct: the
    //    cold-resume re-scan in `step2_resume_scan` rebuilds the set and
    //    re-applies the order via the reconcile seam). When the set IS
    //    populated (the resume-scan completion seam already calls this
    //    recipe) the persisted order marks onto it.
    apply_order_to_mods(&workspace.order_bgee, &mut wizard_state.step2.bgee_mods);
    apply_order_to_mods(&workspace.order_bg2ee, &mut wizard_state.step2.bg2ee_mods);
    // IWDEE: BIO routes IWDEE installs through the BGEE mod set / tab (single
    // game). Apply IWDEE order onto the BGEE mods when this is an IWDEE
    // modlist so a persisted IWDEE selection reconstructs.
    if entry.game == Game::IWDEE {
        apply_order_to_mods(&workspace.order_iwdee, &mut wizard_state.step2.bgee_mods);
    }
    recompute_mod_checked(&mut wizard_state.step2.bgee_mods);
    recompute_mod_checked(&mut wizard_state.step2.bg2ee_mods);

    // Keep `next_selection_order` ahead of the largest restored order so the
    // next user check appends after the restored list (matches BIO's
    // contract for `selected_order`).
    let max_order = max_selected_order(&wizard_state.step2.bgee_mods)
        .max(max_selected_order(&wizard_state.step2.bg2ee_mods));
    wizard_state.step2.next_selection_order = max_order + 1;

    // 4. Step 3 order reconstruction — BIO's own canonical builder. This
    //    produces the parent-header rows + ordered component rows exactly as
    //    BIO's live Step 2→3 sync does.
    wizard_state.step3.bgee_items = step3_sync::build_step3_items(&wizard_state.step2.bgee_mods);
    wizard_state.step3.bg2ee_items = step3_sync::build_step3_items(&wizard_state.step2.bg2ee_mods);

    // 5. Step 3 group-collapse restore (this one IS a WizardState field).
    wizard_state.step3.bgee_collapsed_blocks = collapsed_blocks_for_tab(workspace, "BGEE");
    wizard_state.step3.bg2ee_collapsed_blocks = collapsed_blocks_for_tab(workspace, "BG2EE");

    // Reset the per-tab Step 3 undo/redo + drag transient state on load (per
    // the plan's open-question: the registry file is the "undo of last
    // resort"; saving the history per workspace is a post-v1 enhancement).
    wizard_state.step3.bgee_undo_stack.clear();
    wizard_state.step3.bg2ee_undo_stack.clear();
    wizard_state.step3.bgee_redo_stack.clear();
    wizard_state.step3.bg2ee_redo_stack.clear();
    wizard_state.step3.bgee_selected.clear();
    wizard_state.step3.bg2ee_selected.clear();
    wizard_state.step3.bgee_anchor = None;
    wizard_state.step3.bg2ee_anchor = None;

    // 6. Step 5 reset — install state is per-active-install, gated by
    //    Phase 7's install concurrency policy, never per-workspace-load.
    wizard_state.step5 = crate::app::state::Step5State::default();
}

/// **Reset the in-memory scanned Step-2/3 set + its transients** (Fix-Run 1,
/// Bug B). Called by `populate_wizard_state_from_workspace` on every modlist
/// load/swap, *before* the persisted order is applied, so the orchestrator's
/// single shared `WizardState` never carries one modlist's scanned mods into
/// another's workspace.
///
/// Clears:
///   - the scanned mod vectors (`step2.{bgee,bg2ee}_mods`) — the leak itself;
///   - the derived Step-3 ordered item lists (`step3.{bgee,bg2ee}_items`) —
///     they are a projection of the Step-2 set and would otherwise show the
///     prior modlist's order until the next sync;
///   - the per-tab Step-2 scan/selection transients (`selected`,
///     `next_selection_order`, `selected_count`, `scan_status`,
///     `last_scan_report`, `is_scanning`) so the cold-resume gate
///     (`step2_resume_scan::maybe_trigger_resume_scan`, which requires an
///     **empty** Step-2 set + **no scan in flight**) re-arms for the
///     swapped-in modlist's own re-scan.
///
/// Step-3 group-collapse / undo-redo / selection transients are reset
/// separately by `populate` itself (sections 5–6) — this helper owns only
/// the *scanned-set* reset so the two concerns stay legible.
fn reset_scanned_step2_set(wizard_state: &mut WizardState) {
    wizard_state.step2.bgee_mods.clear();
    wizard_state.step2.bg2ee_mods.clear();
    wizard_state.step3.bgee_items.clear();
    wizard_state.step3.bg2ee_items.clear();
    wizard_state.step2.selected = None;
    wizard_state.step2.next_selection_order = 1;
    wizard_state.step2.selected_count = 0;
    wizard_state.step2.scan_status.clear();
    wizard_state.step2.last_scan_report = None;
    wizard_state.step2.is_scanning = false;
}

/// Mark each `order` `ComponentRef` onto its matching scanned component:
/// `checked = true` and `selected_order = Some(position)`. Components present
/// in the scan but absent from `order` are explicitly unchecked + cleared so
/// a swap to a different modlist's order produces a clean Step 2 state (no
/// stale checks bleed across modlists).
fn apply_order_to_mods(order: &[ComponentRef], mods: &mut [Step2ModState]) {
    // First clear everything so a modlist swap starts from a clean slate.
    for mod_state in mods.iter_mut() {
        for component in &mut mod_state.components {
            component.checked = false;
            component.selected_order = None;
        }
    }
    for (position, item) in order.iter().enumerate() {
        let want_tp2 = item.tp2.to_ascii_uppercase();
        let want_id = item.id.to_string();
        for mod_state in mods.iter_mut() {
            if mod_state.tp_file.to_ascii_uppercase() != want_tp2 {
                continue;
            }
            for component in &mut mod_state.components {
                if component.component_id == want_id {
                    component.checked = true;
                    // `selected_order` is 1-based in BIO (`next_selection_order`
                    // starts at 1); preserve the persisted order index.
                    component.selected_order = Some(position + 1);
                }
            }
        }
    }
}

/// Re-derive each mod's tri-state `checked` flag: a mod is `checked` iff at
/// least one of its components is checked (matches BIO's mod-row marker
/// semantics, where `▣`/`◩`/`☐` is computed from the leaves).
fn recompute_mod_checked(mods: &mut [Step2ModState]) {
    for mod_state in mods.iter_mut() {
        mod_state.checked = mod_state.components.iter().any(|c| c.checked);
    }
}

fn max_selected_order(mods: &[Step2ModState]) -> usize {
    mods.iter()
        .flat_map(|m| m.components.iter())
        .filter_map(|c| c.selected_order)
        .max()
        .unwrap_or(0)
}

/// Map the workspace's flat `step3_group_collapse` map back into the
/// per-tab collapsed-block vectors. Keys are stored `<TAB>::<block_id>` so
/// the two tabs don't collide.
fn collapsed_blocks_for_tab(workspace: &ModlistWorkspaceState, tab: &str) -> Vec<String> {
    let prefix = format!("{tab}::");
    let mut out: Vec<String> = workspace
        .step3_group_collapse
        .iter()
        .filter(|(_, collapsed)| **collapsed)
        .filter_map(|(key, _)| key.strip_prefix(&prefix).map(ToString::to_string))
        .collect();
    out.sort();
    out
}

// ---------------------------------------------------------------------------
// pre-extract Step-2 → Step-3 sync (Fix-Run 1, Bug A)
// ---------------------------------------------------------------------------

/// **Make the live Step-2 selection visible to `extract` (Fix-Run 1, Bug A).**
///
/// `extract_workspace_state_from_wizard` derives the persisted order
/// **exclusively** from `wizard_state.step3.{bgee,bg2ee}_items` (via
/// `order_from_items`). BIO's reused Step-2 component-tree checkbox
/// (`bio::ui::step2::tree::tree_component_row_step2`) mutates only
/// `wizard_state.step2.<tab>_mods[].components[].checked` /
/// `.selected_order` — it emits **no `Step2Action`** and does **not** touch
/// Step 3. BIO propagates a Step-2 selection into Step 3 only on the
/// **Next-from-Step-2** nav edge (`sync_step3_from_step2`, gated by
/// `bio::app::app_nav::decide_next_action`'s selection-change signature).
/// So a user who toggles a Step-2 checkbox and then navigates **Home**
/// (or save-draft / the debounced write) without first advancing to Step 3
/// leaves Step 3 holding the *pre-toggle* order — and `extract` persists
/// that stale order, silently dropping the edit (the reported round-trip
/// bug). Every write path therefore calls this **immediately before**
/// `extract_workspace_state_from_wizard` so the persisted order reflects
/// the current Step-2 selection.
///
/// **BIO-faithful + Step-3-reorder-safe.** This replicates *exactly* the
/// shipped, reviewed `workspace_view::sync_step3_from_step2_on_nav_edge`
/// pattern: it asks BIO's own `pub(crate)` `decide_next_action` (a pure
/// `&WizardState` read; `current_step` is briefly set to BIO's Step-2 index
/// `1` so it evaluates the Step-2 branch, then restored) for the action,
/// and runs BIO's own `pub(crate)` `sync_step3_from_step2` +
/// `set_last_step2_sync_signature` **only** when it returns
/// `SyncStep3AndAdvance` (i.e. the Step-2 selection changed since the last
/// sync, or Step 3 has no real items). When the user only reordered in
/// Step 3 and the Step-2 selection is unchanged, `decide_next_action`
/// returns a non-sync variant ⇒ this is a **no-op** and the user's Step-3
/// drag order is preserved (BIO's own clobber-protection — the `9b5b9d5`
/// concern; never re-introduced here). Zero BIO edits; zero logic copied
/// (the change-detection signature is BIO's own, carried in the enum
/// payload).
///
/// Known narrow limitation (documented, out of this focused run's scope):
/// `decide_next_action` first checks `can_advance_from_current_step`, which
/// at Step 2 requires a non-empty selection — so if the user de-selects
/// **every** component then navigates away, the sync does not run and the
/// last non-empty order persists. That edge pre-exists identically in the
/// shipped Next-from-Step-2 path; closing it would need either a BIO edit
/// to expose `step2_selection_signature` (a PLAN GAP) or net-new signature
/// logic that risks drift — neither is in scope for this round-trip fix.
pub fn sync_step3_from_step2_if_changed(wizard_state: &mut WizardState) {
    use crate::app::app_nav::{NextAction, decide_next_action};
    use crate::app::app_step3_sync_flow::sync_step3_from_step2;

    // Present "we are on Step 2" to BIO's pure decision fn (BIO's Step-2
    // index is 1), then restore — `decide_next_action` does not mutate.
    let saved_step = wizard_state.current_step;
    wizard_state.current_step = 1;
    let action = decide_next_action(wizard_state);
    wizard_state.current_step = saved_step;

    // Replicate ONLY `advance_after_next`'s `SyncStep3AndAdvance` arm
    // (`app_nav_actions.rs:137-140`) — BIO's own sync + signature write.
    if let NextAction::SyncStep3AndAdvance { signature } = action {
        sync_step3_from_step2(wizard_state);
        wizard_state.set_last_step2_sync_signature(signature);
    }
}

// ---------------------------------------------------------------------------
// extract: WizardState → ModlistWorkspaceState
// ---------------------------------------------------------------------------

/// Read the relevant `pub` fields out of `WizardState` to produce a
/// `ModlistWorkspaceState` for the store. The inverse of
/// `populate_wizard_state_from_workspace`.
///
/// Callers (save-draft P6.T6, nav-away P6.T15, debounce P6.T11) land in
/// Runs 2/4 — extract is implemented + unit-tested this run but ships unwired,
/// which is correct.
///
/// `prior` is the workspace state currently on disk / in memory; its
/// `expand_state` (egui-side, no `WizardState` counterpart — see module
/// header) is carried through unchanged so a save doesn't drop it.
pub fn extract_workspace_state_from_wizard(
    wizard_state: &WizardState,
    prior: &ModlistWorkspaceState,
) -> ModlistWorkspaceState {
    let order_bgee = order_from_items(&wizard_state.step3.bgee_items);
    let order_bg2ee = order_from_items(&wizard_state.step3.bg2ee_items);

    // IWDEE shares the BGEE tab/mod set in BIO. When this is an IWDEE
    // workspace mirror the BGEE-derived order into `order_iwdee` so the
    // persisted file reflects the IWDEE selection; otherwise keep whatever
    // the prior file held (non-IWDEE modlists never touch order_iwdee).
    let order_iwdee = if wizard_state.step1.game_install == "IWDEE" {
        order_bgee.clone()
    } else {
        prior.order_iwdee.clone()
    };

    let mut step3_group_collapse = prior.step3_group_collapse.clone();
    write_collapsed_blocks(
        &mut step3_group_collapse,
        "BGEE",
        &wizard_state.step3.bgee_collapsed_blocks,
    );
    write_collapsed_blocks(
        &mut step3_group_collapse,
        "BG2EE",
        &wizard_state.step3.bg2ee_collapsed_blocks,
    );

    ModlistWorkspaceState {
        order_bgee,
        order_bg2ee,
        order_iwdee,
        // Step 2 mod/parent expand state is egui frame memory, not a
        // WizardState field — carry the persisted map through unchanged.
        expand_state: prior.expand_state.clone(),
        step3_group_collapse,
        // Per-workspace prompt overrides: no orchestrator write path exists
        // yet (Step 3 prompt-edit lands via BIO's internal handlers and is
        // not yet mirrored into the workspace file in Run 1); preserve the
        // prior map so a save doesn't drop user overrides.
        prompt_overrides: prior.prompt_overrides.clone(),
        // `last_share_code` is regenerated post-install by Phase 7; carry
        // through whatever the prior file had.
        last_share_code: prior.last_share_code.clone(),
        // The dev-scan source folder (the #1 fix) has no `WizardState`
        // counterpart — it is set directly by the dev-scan trigger and
        // persisted there. Carry the prior value through unchanged so an
        // unrelated save (save-draft / debounce) never drops it.
        dev_scanned_mods_folder: prior.dev_scanned_mods_folder.clone(),
    }
}

/// Project the Step 3 ordered item list into the persisted `ComponentRef`
/// vector. Synthetic parent-header rows (`is_parent` / `__PARENT__`) are
/// skipped — `build_step3_items` regenerates them on populate.
fn order_from_items(items: &[Step3ItemState]) -> Vec<ComponentRef> {
    items
        .iter()
        .filter(|item| !item.is_parent && item.component_id != PARENT_PLACEHOLDER_ID)
        .filter_map(|item| {
            // Component ids are numeric in WeiDU; a non-numeric id here is a
            // synthetic row we don't persist.
            let id = item.component_id.trim().parse::<i64>().ok()?;
            Some(ComponentRef {
                tp2: item.tp_file.clone(),
                id,
                // TP2 LANGUAGE index: BIO's Step 2/3 model does not surface a
                // per-component language on `Step3ItemState`; the project
                // installs at the scan's resolved locale. 0 is the canonical
                // default (matches `ComponentRef::default`); a future
                // language-aware enhancement can widen this.
                language: 0,
            })
        })
        .collect()
}

/// Write the per-tab collapsed-block list into the flat persisted map under
/// the `<TAB>::` prefix. Any previously-stored keys for this tab that are no
/// longer collapsed are dropped so the map doesn't accrete stale entries.
fn write_collapsed_blocks(
    map: &mut std::collections::HashMap<String, bool>,
    tab: &str,
    collapsed: &[String],
) {
    let prefix = format!("{tab}::");
    map.retain(|key, _| !key.starts_with(&prefix));
    for block_id in collapsed {
        map.insert(format!("{prefix}{block_id}"), true);
    }
}

// ---------------------------------------------------------------------------
// sync_paths_from_settings: Step1Settings → wizard_state.step1
// ---------------------------------------------------------------------------

/// Mirror the canonical global path / tool fields from Settings → Paths /
/// Tools (Phase 4) into `wizard_state.step1`. Called **once on workspace
/// open** (from `populate_wizard_state_from_workspace`) — a defensive
/// re-assert, not a per-frame sync.
///
/// Pure copy of the path/tool fields only. It explicitly does **not** touch
/// `game_install` (per-modlist, owned by the loader — SPEC §5.1) nor any
/// Step 2/3/5 state.
///
/// **Global paths come from Settings → Paths, not the workspace.** The
/// workspace screen does not collect game paths; this sync is how Step 2's
/// scan gets a mods folder.
///
/// **Why open-only suffices (no per-frame sync).** The orchestrator's
/// Settings → Paths tab edits the *same in-memory* `wizard_state.step1` the
/// workspace renders from (`OrchestratorApp::wizard_state`; `tab_paths.rs`),
/// so a Settings change is visible to the active workspace **by
/// construction** — there is no second source to reconcile per frame.
/// `SettingsStore` is a path-only handle (no in-memory accessor;
/// `bio_settings.json` is the debounced persisted form), so this open-time
/// call does one `settings_store.load()` as a defensive re-assert of the
/// last-persisted paths; a load error is a silent no-op because the live
/// `wizard_state.step1` already holds current values. SPEC §13.14's
/// "propagate without close/reopen" intent is met by the shared state, not a
/// per-frame disk read (plan M2 amended — overview 2026-05-16).
pub fn sync_paths_from_settings(settings_store: &SettingsStore, wizard_state: &mut WizardState) {
    // `Step1Settings -> Step1State` is the canonical `From` mapping (BIO
    // `state_convert.rs`). We can't wholesale-replace `wizard_state.step1`
    // (that would clobber the per-modlist `game_install` + Step-2-mode
    // flags); copy only the path/tool fields.
    let Ok(settings) = settings_store.load() else {
        return;
    };
    let from: crate::app::state::Step1State = settings.step1.into();
    let dst = &mut wizard_state.step1;

    // Game source folders.
    dst.bgee_game_folder = from.bgee_game_folder;
    dst.bg2ee_game_folder = from.bg2ee_game_folder;
    dst.iwdee_game_folder = from.iwdee_game_folder;
    dst.eet_bgee_game_folder = from.eet_bgee_game_folder;
    dst.eet_bg2ee_game_folder = from.eet_bg2ee_game_folder;

    // WeiDU-log folders / files.
    dst.bgee_log_folder = from.bgee_log_folder;
    dst.bgee_log_file = from.bgee_log_file;
    dst.bg2ee_log_folder = from.bg2ee_log_folder;
    dst.bg2ee_log_file = from.bg2ee_log_file;
    dst.eet_bgee_log_folder = from.eet_bgee_log_folder;
    dst.eet_bg2ee_log_folder = from.eet_bg2ee_log_folder;
    dst.weidu_log_folder = from.weidu_log_folder;
    dst.log_file = from.log_file;

    // EET derived dirs.
    dst.eet_pre_dir = from.eet_pre_dir;
    dst.eet_new_dir = from.eet_new_dir;
    dst.generate_directory = from.generate_directory;

    // Mods folders.
    dst.mods_folder = from.mods_folder;
    dst.mods_archive_folder = from.mods_archive_folder;
    dst.mods_backup_folder = from.mods_backup_folder;

    // Tool binaries.
    dst.weidu_binary = from.weidu_binary;
    dst.mod_installer_binary = from.mod_installer_binary;
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::app::state::{Step2ComponentState, Step2ModState};
    use crate::registry::model::{Game, ModlistEntry, ModlistState};

    fn comp(id: &str, label: &str) -> Step2ComponentState {
        Step2ComponentState {
            component_id: id.to_string(),
            label: label.to_string(),
            weidu_group: None,
            collapsible_group: None,
            collapsible_group_is_umbrella: false,
            raw_line: format!("~MOD/MOD.TP2~ #0 #{id} // {label}"),
            prompt_summary: None,
            prompt_events: Vec::new(),
            is_meta_mode_component: false,
            disabled: false,
            compat_kind: None,
            compat_source: None,
            compat_related_mod: None,
            compat_related_component: None,
            compat_graph: None,
            compat_evidence: None,
            disabled_reason: None,
            checked: false,
            selected_order: None,
        }
    }

    fn mod_state(name: &str, tp_file: &str, comps: Vec<Step2ComponentState>) -> Step2ModState {
        Step2ModState {
            name: name.to_string(),
            tp_file: tp_file.to_string(),
            tp2_path: format!("/mods/{tp_file}"),
            readme_path: None,
            ini_path: None,
            web_url: None,
            package_marker: None,
            latest_checked_version: None,
            update_locked: false,
            mod_prompt_summary: None,
            mod_prompt_events: Vec::new(),
            checked: false,
            hidden_components: Vec::new(),
            components: comps,
        }
    }

    fn entry(game: Game) -> ModlistEntry {
        ModlistEntry {
            id: "ABCDEFGHIJKL".to_string(),
            name: "Test".to_string(),
            game,
            state: ModlistState::InProgress,
            ..Default::default()
        }
    }

    /// The make-or-break test: populate must reconstruct the Step 2 checked
    /// state AND the Step 3 ordered item list from a persisted order — not
    /// just `game_install`.
    #[test]
    fn populate_reconstructs_step2_and_step3_from_order() {
        let mut ws = WizardState::default();

        // Persisted order: BG1UB #0 first, then EEFixPack #2 (deliberately
        // not the scan order, to prove order is honored).
        let mut workspace = ModlistWorkspaceState::default();
        workspace.order_bgee = vec![
            ComponentRef {
                tp2: "BG1UB/SETUP-BG1UB.TP2".to_string(),
                id: 0,
                language: 0,
            },
            ComponentRef {
                tp2: "EEFIXPACK/EEFIXPACK.TP2".to_string(),
                id: 2,
                language: 0,
            },
        ];

        populate_wizard_state_from_workspace(
            &workspace,
            &entry(Game::BGEE),
            &SettingsStore::new_default(),
            &mut ws,
        );

        // Fix-Run 1 (Bug B): populate RESETS the scanned set, so right
        // after populate the set is empty (the cold-resume re-scan
        // repopulates it in the live flow — modelled next).
        assert!(
            ws.step2.bgee_mods.is_empty(),
            "Bug B: populate resets the scanned set (re-scan repopulates)"
        );

        // The cold-resume scan lands the scanned mods (BIO's cache-fed
        // scan; supplied directly), then the reconcile/populate recipe
        // re-applies the persisted order — exactly what
        // `step2_rescan_reconcile`'s `resume_pending` branch does on the
        // scan-completion edge in the live flow.
        ws.step2.bgee_mods = vec![
            mod_state(
                "EEFixPack",
                "EEFIXPACK/EEFIXPACK.TP2",
                vec![comp("0", "Core Fixes"), comp("2", "Game Text Update")],
            ),
            mod_state(
                "BG1UB",
                "BG1UB/SETUP-BG1UB.TP2",
                vec![comp("0", "Restored")],
            ),
        ];
        apply_order_to_mods(&workspace.order_bgee, &mut ws.step2.bgee_mods);
        recompute_mod_checked(&mut ws.step2.bgee_mods);
        let max_order =
            max_selected_order(&ws.step2.bgee_mods).max(max_selected_order(&ws.step2.bg2ee_mods));
        ws.step2.next_selection_order = max_order + 1;
        ws.step3.bgee_items = step3_sync::build_step3_items(&ws.step2.bgee_mods);

        // game_install set (by populate, before the reset — it's Step-1
        // state, untouched by the Step-2 reset).
        assert_eq!(ws.step1.game_install, "BGEE");

        // Step 2: exactly the two ordered components are checked with the
        // persisted order; the third (EEFixPack #0) stays unchecked.
        let eefix = &ws.step2.bgee_mods[0];
        let bg1ub = &ws.step2.bgee_mods[1];
        assert!(!eefix.components[0].checked, "EEFixPack #0 must stay off");
        assert!(eefix.components[1].checked, "EEFixPack #2 must be on");
        assert_eq!(eefix.components[1].selected_order, Some(2));
        assert!(bg1ub.components[0].checked, "BG1UB #0 must be on");
        assert_eq!(bg1ub.components[0].selected_order, Some(1));
        // Mod tri-state re-derived.
        assert!(eefix.checked);
        assert!(bg1ub.checked);

        // Step 3: real reconstruction — BIO's build_step3_items produces
        // parent rows + the two component rows in persisted order.
        let leaves: Vec<&Step3ItemState> = ws
            .step3
            .bgee_items
            .iter()
            .filter(|i| !i.is_parent)
            .collect();
        assert_eq!(leaves.len(), 2, "two component rows expected");
        // BG1UB #0 (selected_order 1) before EEFixPack #2 (selected_order 2).
        assert_eq!(leaves[0].tp_file, "BG1UB/SETUP-BG1UB.TP2");
        assert_eq!(leaves[0].component_id, "0");
        assert_eq!(leaves[1].tp_file, "EEFIXPACK/EEFIXPACK.TP2");
        assert_eq!(leaves[1].component_id, "2");
        // At least one synthetic parent header row was generated.
        assert!(ws.step3.bgee_items.iter().any(|i| i.is_parent));
        // next_selection_order is past the largest restored order.
        assert_eq!(ws.step2.next_selection_order, 3);
    }

    /// extract must be the inverse: a populated WizardState extracts back to
    /// an equivalent order (parent rows dropped, component refs preserved in
    /// order).
    #[test]
    fn extract_is_inverse_of_populate_for_order() {
        let mut ws = WizardState::default();
        let mut workspace = ModlistWorkspaceState::default();
        workspace.order_bgee = vec![
            ComponentRef {
                tp2: "EEFIXPACK/EEFIXPACK.TP2".to_string(),
                id: 0,
                language: 0,
            },
            ComponentRef {
                tp2: "EEFIXPACK/EEFIXPACK.TP2".to_string(),
                id: 2,
                language: 0,
            },
        ];
        populate_wizard_state_from_workspace(
            &workspace,
            &entry(Game::BGEE),
            &SettingsStore::new_default(),
            &mut ws,
        );
        // Fix-Run 1 (Bug B): populate resets the set; model the cold-resume
        // scan landing + the populate/reconcile recipe re-applying the
        // persisted order (the live flow) before the inverse extract.
        ws.step2.bgee_mods = vec![mod_state(
            "EEFixPack",
            "EEFIXPACK/EEFIXPACK.TP2",
            vec![comp("0", "Core"), comp("2", "GTU")],
        )];
        apply_order_to_mods(&workspace.order_bgee, &mut ws.step2.bgee_mods);
        recompute_mod_checked(&mut ws.step2.bgee_mods);
        ws.step3.bgee_items = step3_sync::build_step3_items(&ws.step2.bgee_mods);

        let extracted = extract_workspace_state_from_wizard(&ws, &workspace);
        assert_eq!(extracted.order_bgee, workspace.order_bgee);
    }

    /// The #1-fix `dev_scanned_mods_folder` has no `WizardState` counterpart;
    /// `extract` must carry it through from `prior` unchanged so an unrelated
    /// save (save-draft / debounce) never drops the dev-scan recording (the
    /// same non-drop guarantee `expand_state` / `prompt_overrides` get).
    #[test]
    fn extract_carries_dev_scan_folder_through() {
        let ws = WizardState::default();
        let prior = ModlistWorkspaceState {
            dev_scanned_mods_folder: Some(r"D:\corpus".to_string()),
            ..Default::default()
        };
        let extracted = extract_workspace_state_from_wizard(&ws, &prior);
        assert_eq!(
            extracted.dev_scanned_mods_folder.as_deref(),
            Some(r"D:\corpus"),
            "extract must not drop the dev-scan folder"
        );
    }

    /// Step 3 group-collapse round-trips through the prefixed flat map.
    #[test]
    fn step3_collapse_round_trips() {
        let mut ws = WizardState::default();
        ws.step3.bgee_collapsed_blocks = vec!["BLOCK_A".to_string(), "BLOCK_B".to_string()];
        ws.step3.bg2ee_collapsed_blocks = vec!["BLOCK_C".to_string()];

        let extracted = extract_workspace_state_from_wizard(&ws, &ModlistWorkspaceState::default());
        // Stored with <TAB>:: prefix so tabs don't collide.
        assert_eq!(
            extracted.step3_group_collapse.get("BGEE::BLOCK_A"),
            Some(&true)
        );
        assert_eq!(
            extracted.step3_group_collapse.get("BG2EE::BLOCK_C"),
            Some(&true)
        );

        // Populate the extracted state back: collapsed blocks come back per
        // tab.
        let mut ws2 = WizardState::default();
        populate_wizard_state_from_workspace(
            &extracted,
            &entry(Game::EET),
            &SettingsStore::new_default(),
            &mut ws2,
        );
        assert!(
            ws2.step3
                .bgee_collapsed_blocks
                .contains(&"BLOCK_A".to_string())
        );
        assert!(
            ws2.step3
                .bgee_collapsed_blocks
                .contains(&"BLOCK_B".to_string())
        );
        assert!(
            ws2.step3
                .bg2ee_collapsed_blocks
                .contains(&"BLOCK_C".to_string())
        );
    }

    /// A modlist swap must not bleed across modlists. **Fix-Run 1 (Bug B):**
    /// the swapped-in modlist's scanned Step-2 set is now **fully reset**
    /// (not merely unchecked-in-place) — a fresh modlist starts with NO
    /// scanned mods until its own scan runs (the cold-resume re-scan path
    /// for a draft, or a user scan for a from-scratch modlist).
    #[test]
    fn swap_clears_prior_selection() {
        let mut ws = WizardState::default();
        ws.step2.bgee_mods = vec![mod_state(
            "EEFixPack",
            "EEFIXPACK/EEFIXPACK.TP2",
            vec![comp("0", "Core")],
        )];
        let mut a = ModlistWorkspaceState::default();
        a.order_bgee = vec![ComponentRef {
            tp2: "EEFIXPACK/EEFIXPACK.TP2".to_string(),
            id: 0,
            language: 0,
        }];
        populate_wizard_state_from_workspace(
            &a,
            &entry(Game::BGEE),
            &SettingsStore::new_default(),
            &mut ws,
        );
        // NOTE: with the Bug-B scanned-set reset, A's order is applied onto
        // an *empty* set here (the cold-resume re-scan would repopulate it
        // in the real flow). The point of THIS test is the swap isolation,
        // exercised below.
        assert!(ws.step2.bgee_mods.is_empty());

        // Re-seed A's scanned set as if A's (cold-resume) scan had landed,
        // so we have a non-empty set to prove the *next* swap clears it.
        ws.step2.bgee_mods = vec![mod_state(
            "EEFixPack",
            "EEFIXPACK/EEFIXPACK.TP2",
            vec![comp("0", "Core")],
        )];
        ws.step2.bgee_mods[0].components[0].checked = true;

        // Swap to a different (empty) modlist.
        let b = ModlistWorkspaceState::default();
        populate_wizard_state_from_workspace(
            &b,
            &entry(Game::BGEE),
            &SettingsStore::new_default(),
            &mut ws,
        );
        assert!(
            ws.step2.bgee_mods.is_empty(),
            "Bug B: a swapped-in fresh modlist must NOT inherit the prior \
             modlist's scanned mod set (it must be fully reset, not just \
             unchecked-in-place)"
        );
        assert!(ws.step3.bgee_items.is_empty());
    }

    // ── Fix-Run 1 — the REQUIRED integration test of the real persistence
    //    round-trip + the in-memory cross-modlist isolation. Pure
    //    in-memory `WizardState` + a **temp** `WorkspaceStore`
    //    (`new_with_path` under `std::env::temp_dir()`) — NEVER
    //    `RegistryStore::new_default()` / the real config dir (the
    //    directive-grade DATA-LOSS test-hygiene rule; the
    //    `persistence_cycle` temp-path precedent). It fails on the pre-fix
    //    code (no `sync_step3_from_step2_if_changed`, no scanned-set reset)
    //    and passes after. ──
    use crate::registry::store_workspace::WorkspaceStore;

    /// Build a one-tab scanned mod set with two components, neither checked.
    fn scanned_eefix() -> Vec<Step2ModState> {
        vec![mod_state(
            "EEFixPack",
            "EEFIXPACK/EEFIXPACK.TP2",
            vec![comp("0", "Core Fixes"), comp("2", "Game Text Update")],
        )]
    }

    fn temp_ws_store(label: &str) -> WorkspaceStore {
        let path = std::env::temp_dir().join(format!(
            "bio_fixrun1_{}_{}_workspace.json",
            std::process::id(),
            label
        ));
        let _ = std::fs::remove_file(&path);
        WorkspaceStore::new_with_path(path)
    }

    /// **Bug A — the real round-trip.** Load modlist A → toggle a Step-2
    /// component **exactly as BIO's reused tree does** (mutate
    /// `step2.<tab>_mods[].components[].checked` + `selected_order`
    /// directly, WITHOUT advancing to Step 3 / syncing) → run the
    /// nav-away write path (`sync_step3_from_step2_if_changed` + `extract`
    /// + `WorkspaceStore::save`) → re-load A into a FRESH `WizardState`
    /// (the cold-resume: `WorkspaceStore::load` + `populate`) → assert the
    /// toggled component is restored, checked, in the persisted order.
    ///
    /// Pre-fix this fails: the toggle never reached `step3.<tab>_items`,
    /// `extract` (which reads only Step 3) persisted the empty/stale order,
    /// and the re-load came up unselected — the exact reported bug.
    #[test]
    fn bug_a_step2_toggle_round_trips_through_nav_away_write() {
        let store = temp_ws_store("bug_a");
        let a_entry = entry(Game::BGEE);

        // (1) Cold open of A: empty persisted workspace; the resume scan
        //     (not modelled here — pure state) would land the scanned set.
        //     We simulate "A's scan landed" by seeding the scanned mods,
        //     then `populate` (which now resets then no-op-applies the
        //     empty order — the real flow's reconcile seam re-applies
        //     order post-scan; here there is no prior order yet).
        let mut ws = WizardState::default();
        let empty_ws = ModlistWorkspaceState::default();
        populate_wizard_state_from_workspace(
            &empty_ws,
            &a_entry,
            &SettingsStore::new_default(),
            &mut ws,
        );
        // The scan lands A's mods (BIO's scan-event handler; supplied
        // directly — equivalent to the cache-fed scan).
        ws.step2.bgee_mods = scanned_eefix();

        // (2) User toggles "Game Text Update" (#2) ON — EXACTLY what BIO's
        //     `tree_component_row_step2` does on a checkbox click: set
        //     `checked` + a `selected_order`; NO Step-3 sync, NO action.
        ws.step2.bgee_mods[0].components[1].checked = true;
        ws.step2.bgee_mods[0].components[1].selected_order = Some(1);
        ws.step2.bgee_mods[0].checked = true;
        // Precondition that demonstrates the bug surface: Step 3 is still
        // empty (the toggle did NOT propagate there on its own).
        assert!(
            ws.step3.bgee_items.is_empty(),
            "the bare toggle must not have synced Step 3 (this is why a \
             Step-3-only extract dropped it pre-fix)"
        );

        // (3) Nav-away write path, verbatim: pre-extract sync (the fix) →
        //     extract → WorkspaceStore::save.
        let prior = empty_ws.clone();
        sync_step3_from_step2_if_changed(&mut ws);
        let extracted = extract_workspace_state_from_wizard(&ws, &prior);
        store.save(&extracted).expect("temp workspace save");

        // The persisted order must now carry the toggled component (pre-fix
        // this vec was empty — the round-trip failure).
        assert_eq!(
            extracted.order_bgee,
            vec![ComponentRef {
                tp2: "EEFIXPACK/EEFIXPACK.TP2".to_string(),
                id: 2,
                language: 0,
            }],
            "Bug A: the Step-2 toggle must reach the persisted order"
        );

        // (4) Cold resume of A: fresh WizardState + load + populate, then
        //     the scan lands A's mods again (cold-resume re-scan) and the
        //     reconcile/populate recipe re-applies the persisted order.
        let reloaded = store.load().expect("temp workspace load");
        let mut ws2 = WizardState::default();
        populate_wizard_state_from_workspace(
            &reloaded,
            &a_entry,
            &SettingsStore::new_default(),
            &mut ws2,
        );
        ws2.step2.bgee_mods = scanned_eefix(); // the resume scan lands
        // Re-apply the persisted order onto the freshly-scanned set — the
        // exact `populate`/reconcile recipe (the cold-resume seam runs this
        // post-scan in the live flow).
        apply_order_to_mods(&reloaded.order_bgee, &mut ws2.step2.bgee_mods);
        recompute_mod_checked(&mut ws2.step2.bgee_mods);
        ws2.step3.bgee_items = step3_sync::build_step3_items(&ws2.step2.bgee_mods);

        // (5) The toggle survived the full round-trip.
        assert!(
            ws2.step2.bgee_mods[0].components[1].checked,
            "Bug A: the toggled component must be checked after resume"
        );
        assert!(
            !ws2.step2.bgee_mods[0].components[0].checked,
            "the untoggled component must stay off"
        );
        let leaves: Vec<&Step3ItemState> = ws2
            .step3
            .bgee_items
            .iter()
            .filter(|i| !i.is_parent)
            .collect();
        assert_eq!(leaves.len(), 1, "exactly the toggled component in Step 3");
        assert_eq!(leaves[0].component_id, "2");
    }

    /// **Bug B — the in-memory scanned set must not leak across modlists.**
    /// A has a scan + a persisted order; B is a fresh modlist (no scan, no
    /// order). load A (restores A's selection) → swap to B (must be EMPTY —
    /// no A leakage) → swap back to A (A's scan + selection restored).
    ///
    /// Pre-fix this fails at the B step: `populate` did not reset the
    /// scanned set, so B inherited A's `step2.bgee_mods` (B would show A's
    /// mods, just unchecked) and the cold-resume gate for A's later re-swap
    /// stayed blocked.
    #[test]
    fn bug_b_scanned_set_does_not_leak_across_modlists() {
        let a_entry = entry(Game::BGEE);
        let b_entry = ModlistEntry {
            id: "BBBBBBBBBBBB".to_string(),
            name: "Fresh".to_string(),
            game: Game::BGEE,
            state: ModlistState::InProgress,
            ..Default::default()
        };

        // A: a persisted order over EEFixPack #0.
        let mut a_ws = ModlistWorkspaceState::default();
        a_ws.order_bgee = vec![ComponentRef {
            tp2: "EEFIXPACK/EEFIXPACK.TP2".to_string(),
            id: 0,
            language: 0,
        }];

        // ── Load A. populate resets then applies the order onto an empty
        //    set; the (modelled) cold-resume scan then lands A's mods and
        //    the populate/reconcile recipe re-applies the order. ──
        let mut ws = WizardState::default();
        populate_wizard_state_from_workspace(
            &a_ws,
            &a_entry,
            &SettingsStore::new_default(),
            &mut ws,
        );
        ws.step2.bgee_mods = scanned_eefix(); // A's scan lands
        apply_order_to_mods(&a_ws.order_bgee, &mut ws.step2.bgee_mods);
        recompute_mod_checked(&mut ws.step2.bgee_mods);
        ws.step3.bgee_items = step3_sync::build_step3_items(&ws.step2.bgee_mods);
        assert!(
            ws.step2.bgee_mods[0].components[0].checked,
            "A's selection is live"
        );

        // ── Swap to B (fresh — empty order, no dev-scan). populate MUST
        //    reset the scanned set so B does NOT inherit A's mods. ──
        let b_ws = ModlistWorkspaceState::default();
        populate_wizard_state_from_workspace(
            &b_ws,
            &b_entry,
            &SettingsStore::new_default(),
            &mut ws,
        );
        assert!(
            ws.step2.bgee_mods.is_empty(),
            "Bug B: fresh modlist B must start with NO scanned mods (A's \
             scanned set must not leak across the swap)"
        );
        assert!(ws.step3.bgee_items.is_empty(), "Bug B: B's Step 3 empty");
        assert!(
            ws.step2.selected.is_none() && ws.step2.next_selection_order == 1,
            "Bug B: B's Step-2 selection transients reset"
        );

        // ── Swap back to A. populate resets again; A's own scan re-lands
        //    (the cold-resume gate is re-armed because the set was empty)
        //    and A's persisted order + selection are restored. ──
        populate_wizard_state_from_workspace(
            &a_ws,
            &a_entry,
            &SettingsStore::new_default(),
            &mut ws,
        );
        ws.step2.bgee_mods = scanned_eefix(); // A's re-scan lands
        apply_order_to_mods(&a_ws.order_bgee, &mut ws.step2.bgee_mods);
        recompute_mod_checked(&mut ws.step2.bgee_mods);
        ws.step3.bgee_items = step3_sync::build_step3_items(&ws.step2.bgee_mods);
        assert!(
            ws.step2.bgee_mods[0].components[0].checked,
            "Bug B: swapping back to A restores A's OWN scan + selection"
        );
        assert_eq!(
            ws.step3.bgee_items.iter().filter(|i| !i.is_parent).count(),
            1,
            "Bug B: A's Step 3 restored on the re-swap"
        );
    }
}
