// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2026 Born2BSalty
//
// `share_paste_code_dialog` — the **`SharePasteCodeDialog`** non-blocking
// `egui::Window` popup (per SPEC §10 / §10.3), opened from the workspace
// header's `Share import code` button **only after a successful install**.
//
// Per SPEC §10.3: title "Share import code", sub "Anyone can paste this
// into BIO → Install to get the same modlist.", a monospace scrollable box
// containing the BIO-MODLIST-V1 code (the `entry.latest_share_code` value
// regenerated by `flip_to_installed` with `allow_auto_install = true` —
// P7.T6), footer `Close` + primary `Copy` (Copy → clipboard + a ~1.5s
// `✓ copied to clipboard` flash). Non-blocking (SPEC §10 — no backdrop, no
// focus trap), bit-for-bit consistent with the redesign's other popups
// (`confirm_dialog.rs` / the reused `fork_info_popup.rs`).
//
// **Run 1 scope.** This file is a **minimal stub** — the dialog's behavior
// is Run 3 (P7.T7, after Run 2 wires the registry `latest_share_code` via
// `share_export::pack_meta` + `flip_to_installed`). Run 1 only needs the
// module to exist + register; nothing calls `render` this run (the
// workspace header's `Share import code` button stays disabled until the
// C3 triple holds — that flip is Run 3 / P7.T5). The signature is fixed to
// the plan's `render(ctx, &mut state, &wizard_state)` shape so Run 3 only
// fills the body. Marked `#[allow(dead_code)]` because no caller exists
// until Run 3 (the established staged-component pattern).
//
// SPEC: §10.3, §10 (non-blocking popup convention).

use eframe::egui;

use crate::app::state::WizardState;
use crate::ui::workspace::step5::state_workspace_step5::WorkspaceStep5State;

/// Render the Share import code dialog when `state.share_dialog_open`.
///
/// **Run 1:** a no-op stub. The dialog body (title / sub / monospace
/// scrollable code box / `Close` + primary `Copy` + copied-flash) is Run 3
/// (P7.T7); Run 1 only establishes the module + the fixed signature so the
/// Run-3 implementation drops in without touching callers. No caller wires
/// this until Run 3, so it is `#[allow(dead_code)]` for now (the staged-
/// component precedent — e.g. Phase-6 inert fields).
#[allow(dead_code)]
pub fn render(_ctx: &egui::Context, _state: &mut WorkspaceStep5State, _wizard_state: &WizardState) {
    // P7.T7 (Run 3): the non-blocking `egui::Window` popup body lands here,
    // reading the share code from the registry entry's `latest_share_code`
    // (the post-`flip_to_installed` value with `allow_auto_install = true`,
    // per SPEC §10.3 / §13.3). Run 1 is intentionally a no-op stub — the
    // header's `Share import code` button is disabled until the C3 triple
    // holds (flip wired in Run 3 / P7.T5), so this is never invoked yet.
}
