// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2026 Born2BSalty

#[path = "../core/app/app.rs"]
pub mod app;
#[path = "../core/app/controller/mod.rs"]
pub mod controller;
#[path = "../core/app/compat_logic.rs"]
pub mod compat_logic;
#[path = "../core/app/compat_rule_runtime.rs"]
pub mod compat_rule_runtime;
#[path = "../core/app/compat_mismatch_eval.rs"]
pub mod compat_mismatch_eval;
#[path = "../core/app/compat_mismatch_scan.rs"]
pub mod compat_mismatch_scan;
#[path = "../core/app/compat_dependency_parse.rs"]
pub mod compat_dependency_parse;
#[path = "../core/app/compat_dependency_runtime.rs"]
pub mod compat_dependency_runtime;
#[path = "../core/app/compat_conflict_parse.rs"]
pub mod compat_conflict_parse;
#[path = "../core/app/compat_setup_tra.rs"]
pub mod compat_setup_tra;
#[path = "../core/app/compat_conflict_runtime.rs"]
pub mod compat_conflict_runtime;
#[path = "../core/app/compat_conflict_scan.rs"]
pub mod compat_conflict_scan;
#[path = "../core/app/compat_deprecated_scan.rs"]
pub mod compat_deprecated_scan;
#[path = "../core/app/compat_missing_dep_scan.rs"]
pub mod compat_missing_dep_scan;
#[path = "../core/app/compat_path_eval.rs"]
pub mod compat_path_eval;
#[path = "../core/app/compat_path_runtime.rs"]
pub mod compat_path_runtime;
#[path = "../core/app/compat_path_scan.rs"]
pub mod compat_path_scan;
#[path = "../core/app/compat_rules.rs"]
pub mod compat_rules;
#[path = "../core/app/compat_step3_rules.rs"]
pub mod compat_step3_rules;
pub mod frame;
#[path = "../core/app/layout.rs"]
pub mod layout;
pub mod run;
#[path = "../core/app/scan/mod.rs"]
pub mod scan;
pub mod shared;
#[path = "../core/app/state.rs"]
pub mod state;
#[path = "../core/app/state_convert.rs"]
pub mod state_convert;
#[path = "../core/app/state_nav.rs"]
pub mod state_nav;
#[path = "../core/app/state_validation.rs"]
pub mod state_validation;
pub mod step1;
pub mod step2;
#[path = "../core/app/step2_worker.rs"]
pub mod step2_worker;
pub mod step3;
pub mod step4;
pub mod step5;
#[path = "../core/app/terminal/mod.rs"]
pub mod terminal;

pub use run::run;
