// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2026 Born2BSalty
//
// Install Preview — Overview "Mods" derivation (SPEC §4.2).
//
// The parsed share-code preview (`ModlistSharePreview`) carries the raw
// per-game weidu.log text but no precomputed mod count, while SPEC §4.2
// and the canonical wireframe (`screens.jsx` `FORK_META.mods`) both pin a
// real `Mods: <count>`. We derive it net-new (no BIO edit) by reusing
// BIO's public `Component::parse_weidu_line` read-only — the directive's
// decision-order option 1 (direct reuse of a `crate::*` public API), NOT
// a hand-rolled parser.
//
// "A mod" in WeiDU is one TP2: a single mod contributes many component
// lines (one weidu.log entry each) but exactly one `<dir>/<tp2>`, so the
// distinct TP2 set across both logs IS the mod count. The line filter
// mirrors `modlist_share::count_weidu_entries` (the same function that
// produces `bgee_entries` / `bg2ee_entries`, i.e. `Components`) so Mods
// and Components are read off one consistent line set: trimmed, non-empty,
// non-`//`. Unparseable lines are skipped (defensive — same spirit as the
// filter); WeiDU paths are case-insensitive, so the key is upper-cased.

use std::collections::HashSet;

use crate::mods::component::Component;

/// Distinct TP2 (== mod) count across both game logs. SPEC §4.2.
pub(crate) fn distinct_mod_count(bgee_log_text: &str, bg2ee_log_text: &str) -> usize {
    let mut mods: HashSet<String> = HashSet::new();
    for text in [bgee_log_text, bg2ee_log_text] {
        for line in text.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with("//") {
                continue;
            }
            if let Ok(component) = Component::parse_weidu_line(line) {
                mods.insert(
                    format!("{}/{}", component.name, component.tp_file).to_ascii_uppercase(),
                );
            }
        }
    }
    mods.len()
}

#[cfg(test)]
mod tests {
    use super::distinct_mod_count;

    #[test]
    fn counts_distinct_tp2_across_both_logs_ignoring_comments_and_blanks() {
        // BGEE: 3 component lines from 2 mods (ASCENSION x2, EET x1) plus a
        // comment line and a blank line that must NOT count.
        let bgee = "\
// generated by WeiDU — ignored

~ASCENSION/ASCENSION.TP2~ #0 #0 // Ascension - by David Wallis: v2.0
~ASCENSION/ASCENSION.TP2~ #0 #10 // Ascension - Improved battles
~EET/EET.TP2~ #0 #0 // EET core: v13";
        // BG2EE: one line re-uses ASCENSION via a case-different path (must
        // dedupe to the same mod), one is a new mod (CDTWEAKS).
        let bg2ee = "\
~ascension/ascension.tp2~ #0 #20 // Ascension - Wrath of the Five Gods
~CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #3160 // Tweaks Anthology: Anthology";
        // Distinct TP2: ASCENSION/ASCENSION.TP2 (deduped across case + log),
        // EET/EET.TP2, CDTWEAKS/SETUP-CDTWEAKS.TP2 == 3.
        assert_eq!(distinct_mod_count(bgee, bg2ee), 3);
    }

    #[test]
    fn empty_or_commentless_logs_yield_zero() {
        assert_eq!(distinct_mod_count("", ""), 0);
        assert_eq!(distinct_mod_count("// only a comment\n\n   \n", ""), 0);
    }
}
