// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2026 Born2BSalty

#[derive(Debug, Clone, Default)]
pub(crate) struct InstallCommandConfig {
    pub(crate) game_install: String,
    pub(crate) have_weidu_logs: bool,
    pub(crate) custom_scan_depth: bool,
    pub(crate) timeout_per_mod_enabled: bool,
    pub(crate) lookback_enabled: bool,
    pub(crate) tick_dev_enabled: bool,
    pub(crate) weidu_log_mode_enabled: bool,
    pub(crate) new_pre_eet_dir_enabled: bool,
    pub(crate) new_eet_dir_enabled: bool,
    pub(crate) generate_directory_enabled: bool,
    pub(crate) mod_installer_binary: String,
    pub(crate) bgee_game_folder: String,
    pub(crate) bgee_log_folder: String,
    pub(crate) bgee_log_file: String,
    pub(crate) bg2ee_game_folder: String,
    pub(crate) bg2ee_log_folder: String,
    pub(crate) bg2ee_log_file: String,
    pub(crate) eet_bgee_game_folder: String,
    pub(crate) eet_bgee_log_folder: String,
    pub(crate) eet_bg2ee_game_folder: String,
    pub(crate) eet_bg2ee_log_folder: String,
    pub(crate) eet_pre_dir: String,
    pub(crate) eet_new_dir: String,
    pub(crate) generate_directory: String,
    pub(crate) mods_folder: String,
    pub(crate) weidu_binary: String,
    pub(crate) language: String,
    pub(crate) depth: usize,
    pub(crate) skip_installed: bool,
    pub(crate) abort_on_warnings: bool,
    pub(crate) timeout: usize,
    pub(crate) weidu_log_mode: String,
    pub(crate) strict_matching: bool,
    pub(crate) download: bool,
    pub(crate) overwrite: bool,
    pub(crate) check_last_installed: bool,
    pub(crate) tick: u64,
    pub(crate) lookback: usize,
    pub(crate) casefold: bool,
}
