// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2026 Born2BSalty

use crate::platform_defaults::{default_mod_installer_binary, default_weidu_binary};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Step1State {
    pub game_install: String,
    pub have_weidu_logs: bool,
    pub rust_log_debug: bool,
    pub rust_log_trace: bool,
    pub custom_scan_depth: bool,
    pub timeout_per_mod_enabled: bool,
    pub auto_answer_initial_delay_enabled: bool,
    pub auto_answer_post_send_delay_enabled: bool,
    pub prompt_required_sound_enabled: bool,
    pub lookback_enabled: bool,
    pub bio_full_debug: bool,
    pub tick_dev_enabled: bool,
    pub log_raw_output_dev: bool,
    pub weidu_log_mode_enabled: bool,
    pub new_pre_eet_dir_enabled: bool,
    pub new_eet_dir_enabled: bool,
    pub generate_directory_enabled: bool,
    pub prepare_target_dirs_before_install: bool,
    pub weidu_log_autolog: bool,
    pub weidu_log_logapp: bool,
    pub weidu_log_logextern: bool,
    pub weidu_log_log_component: bool,
    pub weidu_log_folder: String,
    pub mod_installer_binary: String,
    pub bgee_game_folder: String,
    pub bgee_log_folder: String,
    pub bgee_log_file: String,
    pub bg2ee_game_folder: String,
    pub bg2ee_log_folder: String,
    pub bg2ee_log_file: String,
    pub eet_bgee_game_folder: String,
    pub eet_bgee_log_folder: String,
    pub eet_bg2ee_game_folder: String,
    pub eet_bg2ee_log_folder: String,
    pub eet_pre_dir: String,
    pub eet_new_dir: String,
    pub game: String,
    pub log_file: String,
    pub generate_directory: String,
    pub mods_folder: String,
    pub weidu_binary: String,
    pub language: String,
    pub depth: usize,
    pub skip_installed: bool,
    pub abort_on_warnings: bool,
    pub timeout: usize,
    pub auto_answer_initial_delay_ms: usize,
    pub auto_answer_post_send_delay_ms: usize,
    pub weidu_log_mode: String,
    pub strict_matching: bool,
    pub download: bool,
    pub overwrite: bool,
    pub check_last_installed: bool,
    pub tick: u64,
    pub lookback: usize,
    pub casefold: bool,
    pub backup_targets_before_eet_copy: bool,
}

impl Default for Step1State {
    fn default() -> Self {
        Self {
            game_install: "BGEE".to_string(),
            have_weidu_logs: false,
            rust_log_debug: false,
            rust_log_trace: false,
            custom_scan_depth: false,
            timeout_per_mod_enabled: false,
            auto_answer_initial_delay_enabled: false,
            auto_answer_post_send_delay_enabled: false,
            prompt_required_sound_enabled: true,
            lookback_enabled: false,
            bio_full_debug: false,
            tick_dev_enabled: false,
            log_raw_output_dev: false,
            weidu_log_mode_enabled: true,
            new_pre_eet_dir_enabled: false,
            new_eet_dir_enabled: false,
            generate_directory_enabled: false,
            prepare_target_dirs_before_install: false,
            weidu_log_autolog: true,
            weidu_log_logapp: true,
            weidu_log_logextern: true,
            weidu_log_log_component: false,
            weidu_log_folder: String::new(),
            mod_installer_binary: default_mod_installer_binary(),
            bgee_game_folder: String::new(),
            bgee_log_folder: String::new(),
            bgee_log_file: String::new(),
            bg2ee_game_folder: String::new(),
            bg2ee_log_folder: String::new(),
            bg2ee_log_file: String::new(),
            eet_bgee_game_folder: String::new(),
            eet_bgee_log_folder: String::new(),
            eet_bg2ee_game_folder: String::new(),
            eet_bg2ee_log_folder: String::new(),
            eet_pre_dir: String::new(),
            eet_new_dir: String::new(),
            game: String::new(),
            log_file: String::new(),
            generate_directory: String::new(),
            mods_folder: String::new(),
            weidu_binary: default_weidu_binary(),
            language: "en_US".to_string(),
            depth: 5,
            skip_installed: true,
            abort_on_warnings: false,
            timeout: 3600,
            auto_answer_initial_delay_ms: 2000,
            auto_answer_post_send_delay_ms: 5000,
            weidu_log_mode: "autolog,logapp,log-extern".to_string(),
            strict_matching: false,
            download: true,
            overwrite: false,
            check_last_installed: true,
            tick: 500,
            lookback: 10,
            casefold: false,
            backup_targets_before_eet_copy: false,
        }
    }
}
