// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2026 Born2BSalty

pub mod action_step2;
#[path = "compat/compat_issue_text_step2.rs"]
pub mod compat_issue_text_step2;
#[path = "compat/compat_popup_nav_step2.rs"]
pub mod compat_popup_nav_step2;
#[path = "compat/compat_popup_step2.rs"]
pub mod compat_popup_step2;
#[path = "compat/compat_types_step2.rs"]
pub mod compat_types_step2;
#[path = "compat/compat_window_step2.rs"]
pub mod compat_window_step2;
pub mod content_step2;
#[path = "details/details_meta_step2.rs"]
pub mod details_meta_step2;
#[path = "details/details_pane_step2.rs"]
pub mod details_pane_step2;
#[path = "details/details_paths_step2.rs"]
pub mod details_paths_step2;
#[path = "details/details_selection_step2.rs"]
pub mod details_selection_step2;
pub mod format_step2;
pub mod frame_step2;
pub mod list_pane_step2;
pub mod page_step2;
#[path = "prompt/prompt_eval_vars_step2.rs"]
pub mod prompt_eval_vars_step2;
#[path = "prompt/prompt_popup_step2.rs"]
pub mod prompt_popup_step2;
#[path = "compat/service_compat_defaults_step2.rs"]
pub mod service_compat_defaults_step2;
#[path = "compat/service_compat_rules_step2.rs"]
pub mod service_compat_rules_step2;
#[path = "services/service_component_parse_step2.rs"]
pub mod service_component_parse_step2;
#[path = "details/service_details_step2.rs"]
pub mod service_details_step2;
#[path = "services/service_list_ops_step2.rs"]
pub mod service_list_ops_step2;
#[path = "services/service_mod_downloads_defaults_step2.rs"]
pub mod service_mod_downloads_defaults_step2;
#[path = "services/service_selection_step2.rs"]
pub mod service_selection_step2;
pub mod state_step2;
#[path = "toolbar/toolbar_actions_step2.rs"]
pub mod toolbar_actions_step2;
#[path = "toolbar/toolbar_compat_step2.rs"]
pub mod toolbar_compat_step2;
#[path = "tree/tree_compat_display_step2.rs"]
pub mod tree_compat_display_step2;
#[path = "tree/tree_component_row_step2.rs"]
pub mod tree_component_row_step2;
#[path = "tree/tree_component_types_step2.rs"]
pub mod tree_component_types_step2;
#[path = "tree/tree_components_step2.rs"]
pub mod tree_components_step2;
#[path = "tree/tree_header_marker_step2.rs"]
pub mod tree_header_marker_step2;
#[path = "tree/tree_parent_step2.rs"]
pub mod tree_parent_step2;
#[path = "tree/tree_render_step2.rs"]
pub mod tree_render_step2;
#[path = "tree/tree_selection_rules_step2.rs"]
pub mod tree_selection_rules_step2;
#[path = "update_check/update_check_popup_lists_step2.rs"]
pub mod update_check_popup_lists_step2;
#[path = "update_check/update_check_popup_report_step2.rs"]
pub mod update_check_popup_report_step2;
#[path = "update_check/update_check_popup_source_editor_step2.rs"]
pub mod update_check_popup_source_editor_step2;
#[path = "update_check/update_check_popup_step2.rs"]
pub mod update_check_popup_step2;
