// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2026 Born2BSalty

pub mod action_step5;
#[path = "content/content_cancel_step5.rs"]
pub mod content_cancel_step5;
#[path = "content/content_dev_header_step5.rs"]
pub mod content_dev_header_step5;
#[path = "content/content_install_row_step5.rs"]
pub mod content_install_row_step5;
#[path = "content/content_step5.rs"]
pub mod content_step5;
pub(crate) use crate::app::step5::diagnostics;
pub mod frame_step5;
pub(crate) use crate::app::step5::log_files;
pub mod menus_step5;
pub mod page_step5;
#[path = "prompts/prompt_answers_rows_step5.rs"]
pub mod prompt_answers_rows_step5;
#[path = "prompts/prompt_answers_step5.rs"]
pub mod prompt_answers_step5;
#[path = "prompts/prompt_answers_table_step5.rs"]
pub mod prompt_answers_table_step5;
#[path = "prompts/prompt_answers_top_bar_step5.rs"]
pub mod prompt_answers_top_bar_step5;
pub(crate) use crate::app::step5::prompt_memory;
#[path = "services/service_diagnostics_support_step5.rs"]
pub mod service_diagnostics_support_step5;
#[path = "services/service_process_line_step5.rs"]
pub mod service_process_line_step5;
#[path = "services/service_prompt_groups_step5.rs"]
pub mod service_prompt_groups_step5;
#[path = "services/service_sound_step5.rs"]
pub mod service_sound_step5;
#[path = "services/service_step5_command_step5.rs"]
pub mod service_step5_command_step5;
#[path = "services/service_timefmt_step5.rs"]
pub mod service_timefmt_step5;
pub mod state_step5;
#[path = "status/status_bar_step5.rs"]
pub mod status_bar_step5;
#[path = "status/status_console_step5.rs"]
pub mod status_console_step5;
#[path = "status/status_input_row_step5.rs"]
pub mod status_input_row_step5;
#[path = "status/status_phase_step5.rs"]
pub mod status_phase_step5;
pub mod top_panels_step5;
